@host = http://localhost:5000

###
GET {{host}}/product-api/api/products?api-version=1.0 HTTP/1.1
content-type: {{contentType}}
x-query: {"filters":[{"fieldName": "Name", "comparision": "Contains", "fieldValue": "test"}],"sorts":["nameDesc"],"page":1,"pageSize":20}

###
@id = 23537dac-303f-446f-be2a-1dbea22b3eba
GET {{host}}/product-api/api/products/{{id}}?api-version=1.0 HTTP/1.1
content-type: {{contentType}}

###
@country-id = 18a4a8ae-3338-484a-a4ed-6e64d13d84dc
GET {{host}}/setting-api/api/countries/{{country-id}} HTTP/1.1
content-type: {{contentType}}

###
POST {{host}}/product-api/api/products?api-version=1.0 HTTP/1.1
content-type: {{contentType}}

{
  "model": {
    "name": "test product 1",
    "quantity": 1,
    "cost": 1000,
    "productCodeName": "pcode"
  }
}

###
POST {{host}}/customer-api/api/customers?api-version=1.0 HTTP/1.1
content-type: {{contentType}}

{
  "model": {
    "firstName": "firstName 1",
    "lastName": "lastName 1",
    "email": "email1@nomail.com",
    "countryId": "18a4a8ae-3338-484a-a4ed-6e64d13d84dc"
  }
}
