@startuml

' title <b>eCommerce Class Diagram</b>

package "Shared Kernel" {
  abstract class EntityBase
  abstract class ValueObject
  interface IAggregateRoot
  abstract class Repository
  abstract class Service
  abstract class DomainService
  abstract class ApplicationService
  abstract class InfrastructureService
}

Repository --> IAggregateRoot
DomainService --|> Service
ApplicationService --|> Service
InfrastructureService --|> Service

package "Product Management" {
  class Product
  class ProductCode
  class Return
  enum ReturnReason

  EntityBase <|-- Product
  EntityBase <|-- ProductCode
  EntityBase <|-- Return

  IAggregateRoot <|.. Product
  IAggregateRoot <|.. ProductCode

  ProductCode --* Product
  Return -left-* Product
  Return *-- ReturnReason
}

package "Customer Management" {
  class Customer
  class CreditCard
  class CustomerPurchaseHistoryReadModel

  EntityBase <|-- Customer
  EntityBase <|-- CreditCard

  IAggregateRoot <|.. CreditCard

  Customer *-- CreditCard
  Customer <.. CustomerPurchaseHistoryReadModel
}

package "Cart Management" {
  class Cart
  class CartProduct
  class Purchase
  class PurchasedProduct
  class Money
  enum CheckOutIssue

  EntityBase <|-- Cart
  EntityBase <|-- CartProduct
  EntityBase <|-- Purchase
  EntityBase <|-- PurchasedProduct

  IAggregateRoot <|.. Cart
  IAggregateRoot <|.. Purchase

  ValueObject <|-- Money

  Cart *-- CartProduct
  Purchase *-- PurchasedProduct
  CartProduct *-left- Money
  Purchase *-- CheckOutIssue

  Cart ..> Customer
  CartProduct ..> Customer
  Purchase ..> Customer
}

package "Settings Management" {
  class Settings
  class Country
  class CountryTax
  class HistoryData
  enum TaxType

  EntityBase <|-- Country
  EntityBase <|-- CountryTax
  EntityBase <|-- HistoryData

  IAggregateRoot <|.. Country
  IAggregateRoot <|.. CountryTax
  IAggregateRoot <|.. HistoryData

  Settings *-- Country
  Settings *-- HistoryData
  CountryTax *-left- TaxType
  Country *-left- CountryTax
}

Return <.. Customer
Customer <.. Country
CartProduct ..> Product
PurchasedProduct ..> Product

@enduml
