// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace ProductService.Infrastructure
{
    partial class MainDbContextModel
    {
        partial void Initialize()
        {
            var product = ProductEntityType.Create(this);
            var productCode = ProductCodeEntityType.Create(this);
            var @return = ReturnEntityType.Create(this);

            ProductEntityType.CreateForeignKey1(product, productCode);
            ReturnEntityType.CreateForeignKey1(@return, product);

            ProductEntityType.CreateAnnotations(product);
            ProductCodeEntityType.CreateAnnotations(productCode);
            ReturnEntityType.CreateAnnotations(@return);

            AddAnnotation("Npgsql:PostgresExtension:uuid-ossp", ",,");
            AddAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);
            AddAnnotation("ProductVersion", "6.0.0-preview.5.21301.9");
            AddAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
